### ISSUE TITLE
ServiceNotFoundError: Service 'http.get' is not found.

### ISSUE THREAD

**Issue by tonychangcheng** [moleculerjs/moleculer-http-client#3]
I am using the Moleculer project template. I have install moleculer-http-client. And I have added the httpClient to the setting. But I got the error "ServiceNotFoundError: Service 'http.get' is not found."

```js
const HTTPClientService = require("moleculer-http-client");


module.exports = {
	name: "greeter",
	mixins: [HTTPClientService],

	settings: {
		// HTTP client settings
		httpClient: {
			// Boolean value indicating whether request should be logged or not
			logging: true,

			// // Log request function
			// logOutgoingRequest: logOutgoingRequest,

			// // Log response function
			// logIncomingResponse: logIncomingResponse,

			// Format the Response
			responseFormatter: "body", // one of "body", "headers", "status", "raw"

			// Format the Errors
			// errorFormatter: errorFormatter,

			// Got Client options
			defaultOptions: {
				// Put here any Got available option that can be used to extend Got client
			}
		}
	},

	/**
	 * Dependencies
	 */
	dependencies: [],

	/**
	 * Actions
	 */
	actions: {

		/**
		 * Say a 'Hello' action.
		 *
		 * @returns
		 */
		hello: {
			rest: {
				method: "GET",
				path: "/hello"
			},
			async handler() {
				this.broker.call('http.get', {
					url: 'https://postman-echo.com/get?foo1=bar1&foo2=bar2'
				});
				return "Hello Moleculer";
			}
		},
	},
};

`

**Comment by AndreMaz** [comment]
@tonychangcheng when you are using [mixins](https://moleculer.services/docs/0.14/services.html#Mixins) you are actually extending the `greeter` service with the [moleculer-http-client ] actions. You are **not** creating another service. This is why when you call `this.broker.call('http.get')` you get a ServiceNotFoundError.

To see how the mixins work comment this line `mixins: [HTTPClientService]`, run the `npm run dev` and then, in terminal, run `actions` command. It will show you the list of the available actions. The greeter will only have 2 actions: `greeter.hello` and `greeter.welcome`. Then put the `mixins: [HTTPClientService]` back and repeat the procedure. You will see that `greeter` service was extended with the `get/post/put/delete` [actions](https://moleculer.services/docs/0.14/actions.html) and `_get/_post/_put/_delete` [methods](https://moleculer.services/docs/0.14/services.html#Methods).

Anyway, try this.
```js
async handler(){
      // Use the _get method to make an http request
      const res = await this._get(request.url, request.opt);
      this.logger.info("Printing Payload");
      // Print the incoming payload
      this.logger.info(res);
}
```

**Comment by tonychangcheng** [comment]
I got it. Thanks for the explain.
